name: ODBC Scanner
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux-amd64:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    env:
      DUCKDB_ODBC_SHARED_LIB_PATH: ${{ github.workspace }}/third_party/duckdb-odbc/libduckdb_odbc.so
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup ODBC env
        shell: bash
        run: |
          sudo apt install unixodbc-dev
          ./resources/scripts/download_odbc_lib.sh linux-amd64
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_SHARED_LIB_PATH}" >> ~/.odbcinst.ini

      - name: Build and Test
        shell: bash
        run: |
          make configure
          make test

  linux-aarch64:
    name: Linux (aarch64)
    runs-on: ubuntu-latest
    needs: linux-amd64
    env:
      DUCKDB_ODBC_SHARED_LIB_PATH: ${{ github.workspace }}/third_party/duckdb-odbc/libduckdb_odbc.so
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup ODBC env
        shell: bash
        run: |
          sudo apt install unixodbc-dev
          ./resources/scripts/download_odbc_lib.sh linux-aarch64
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_SHARED_LIB_PATH}" >> ~/.odbcinst.ini

      - name: Build and Test
        shell: bash
        run: |
          make configure
          make test

  osx-universal:
    name: ODBC OSX (Universal)
    runs-on: macos-14
    env:
      GEN: ninja
      OSX_BUILD_UNIVERSAL: 1
      DUCKDB_ODBC_SHARED_LIB_PATH: ${{ github.workspace }}/third_party/duckdb-odbc/libduckdb_odbc.dylib
    needs: linux-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup ODBC env
        shell: bash
        run: |
          brew install unixodbc
          ./resources/scripts/download_odbc_lib.sh osx-universal
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_SHARED_LIB_PATH}" >> ~/.odbcinst.ini

      - name: Build and Test
        shell: bash
        run: |
          make configure
          make test
        
