name: ODBC Scanner
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install --user clang_format==11.0.1
          python ./resources/scripts/format.py --check 

  linux-amd64:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    needs: format-check
    env:
      GEN: ninja
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.so
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Dependencies
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            unixodbc-dev \
            ninja-build

      - name: Download Shared Libs
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-linux-amd64.zip
          unzip -q duckdb_odbc-linux-amd64.zip
          ls -laR
          popd
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Configure
        run: |
          make configure

      - name: Build
        run: |
          make release

      - name: Setup ODBC Env
        run: |
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_LIB_PATH}" >> ~/.odbcinst.ini
          cat ~/.odbcinst.ini

      - name: SQL Tests
        run: |
          make test

      - name: C API Tests
        run: |
          make test_c_api

  osx-universal:
    name: MacOS (aarch64)
    runs-on: macos-latest
    needs: linux-amd64
    env:
      GEN: ninja
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.dylib
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.dylib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Dependencies
        run: |
          brew install \
            unixodbc \
            ninja

      - name: Download Shared Libs
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-osx-universal.zip
          unzip -q duckdb_odbc-osx-universal.zip
          ls -laR
          popd
          ./resources/scripts/macos_update_downloaded_lib.sh ${DUCKDB_ODBC_LIB_PATH}
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-osx-universal.zip
          unzip -q libduckdb-osx-universal.zip
          ls -laR
          popd

      - name: Configure
        run: |
          make configure

      - name: Build
        run: |
          make release

      - name: Setup ODBC Env
        run: |
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_LIB_PATH}" >> ~/.odbcinst.ini
          cat ~/.odbcinst.ini

      - name: SQL Tests
        run: |
          make test

      - name: C API Tests
        run: |
          make test_c_api
